spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/get_together
    username: root
    password: 111
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    database: mysql
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
  main:
    banner-mode: console
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    path: /api-docs-ui
    supported-submit-methods: []

server:
  port: 8888
  error:
    include-binding-errors: always
    include-message: always